### ISSUE TITLE
Audio working but video not displayed

### ISSUE THREAD

**Issue by diazweb** [LegionFu/VLC_Player#2]
I can hear the audio but the video is not displayed on the parent material. I'm using a media texture.

Btw, your Content folder is not correctly uploaded to Github, would be great if you can reupload the files correctly so we have an example working.

Thanks!

**Comment by LegionFu** [comment]
thanks for your reminder, I'll fix it later.

**Comment by LegionFu** [comment]
thanks for your reminder, I'll fix it later.

**Comment by LegionFu** [comment]
You can try to clone this repository, it should be fixed. And you can open the ExampleMap in plugin content, it can help you use this plugin.
