### ISSUE TITLE
Are you open for a freelance work?

### ISSUE THREAD

**Issue by hollyopk** [LegionFu/VLC_Player#3]
I want to hire you as a developer to implement this VLC plugin to our project workflow, do you have any way to get in contact?

Thanks!
Abraham Kim

**Comment by LegionFu** [comment]
Thank you for your approval, but so sorry, I already have a job. You can tell me your needs, and I can try to help you.

Legion  : )

**Comment by hollyopk** [comment]
Oh okay, nice to hear from you!

I can see you did not use LFS to upload so the plugin is missing some libraries, would be awesome if you can zip the plugin and send in another drive provider, please?

Thank you very much!

**Comment by LegionFu** [comment]
You can try to clone this repository again, it should be fixed.
