### ISSUE TITLE
您好，我想问下视频墙的播放器插件需要怎么做

### ISSUE THREAD

**Issue by 17702513221** [LegionFu/VLC_Player#4]
我尝试过opencv和https://github.com/bakjos/FFMPEGMedia的FFMPEG版本，资源消耗都太大了

**Comment by LegionFu** [comment]
自己调FFmpeg的库写一个吧，性能会好很多，FFmpeg解码后的画面显示可以参考这个工程。

**Comment by LegionFu** [comment]
我写的插件因为是给公司用的，所以不方便放出来 : )
